## DESCRIPTIV STATISTICS

[0,4,8] umur

rata- rata (mean) = 4

n = 3

stdev = 0-4 dikuadratkan = 16 + 4-4 + 4dikuadratkan=16)/3-1

stdev = ((16 + 0 + 16)/3-1^1/2 = (32/2)^1/2 = 4 tahun

variance = 16 tahun kuadrat
         
- persentil : untuk merepresentasikan suatu nilai dlm kumpulan data
- persentil 1 paling bawah 100 atas
- quartil dibagi 4 bagian
- interquartil untk mendeteksi outlayer



# skewness
apakh distribusi normal positif atau negatif skew
# kurtosis
- mesokurtic : distribusi yng memiliki kurtosis serupa dg kurtosis berdistribusi normal, yaitu nol
- leptokurtic : memiliki kurtosis lebih besar dr distribusi mesokurtik
- platykurtic : memiliki kurtosis lebih rendah dr distribusi mesokurtik
# correlation
yaitu teknik statistik yng dpt menunjukkan apakah dan seberapa kuat variabel terkait/related.

In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
math.nan

nan

In [3]:
np.nan

nan

In [4]:
x = [8, 1, 2.5, 4, 28]
x_with_nan = [8, 1, 2.5, math.nan, 4, 28]
print(x)
print(x_with_nan)

[8, 1, 2.5, 4, 28]
[8, 1, 2.5, nan, 4, 28]


In [5]:
# buat array sbg y dan series z dari x
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [6]:
z_with_nan.isna()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

# central tendency

## mean (aritmatik mean)

1. x list
2. y
3. x series

In [7]:
x

[8, 1, 2.5, 4, 28]

In [8]:
sum(x)

43.5

In [9]:
len(x)

5

In [10]:
mean_x = sum(x)/len(x)
mean_x

8.7

In [11]:
mean_stats = statistics.mean(x)
print(mean_stats)

8.7


In [12]:
mean_np = np.mean(x)
print(mean_np)

8.7


In [13]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [14]:
y.mean() # array

8.7

In [15]:
z.mean() # series

8.7

In [16]:
y_with_nan.mean()

nan

In [17]:
np.mean(y_with_nan)

nan

In [18]:
np.nan*3

nan

In [19]:
np.nanmean(y_with_nan)

8.7

In [20]:
z_with_nan.mean() # series langsung merataratakan tanpa mempertimbangkan nan values

8.7

In [21]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

## weighted mean
yaitu rata rata dg menghitung pembobotan (w/weigh)

In [22]:
x = [8, 1, 2.5, 4, 28] #metrik
w = [0.1,0.2,0.3,0.25,0.15] # weightages

#convert jdi array
y,z,w = np.array(x),pd.Series(x),np.array(w)

wmean = np.average(y , weights=w)
print(wmean)

6.95


In [23]:
np.mean(x)

8.7

In [24]:
# manual calculation
wmean_manual = sum(w[i]*x[i] for i in range(len(x)))/sum(w)
print(wmean)

6.95


In [25]:
sum(w)

1.0

## harmonic mean

sering dipakai untuk rata rata rate contohnya 10km/jam, 100kg/hari, 100000orang/th

conto punya 10km at 60 km/h

In [26]:
speed = [60,20]
hmean_speed = len(speed)/sum(1/item for item in speed)
hmean_speed

30.0

In [27]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [28]:
arit_mean = np.mean(x)
arit_mean

8.7

In [29]:
x

[8, 1, 2.5, 4, 28]

In [30]:
for item in x :
    print(1/item)

0.125
1.0
0.4
0.25
0.03571428571428571


In [31]:
sum (1/item for item in x)

1.8107142857142857

In [32]:
list (1/item for item in x)

[0.125, 1.0, 0.4, 0.25, 0.03571428571428571]

In [33]:
hmean_speed_stats = statistics.harmonic_mean(speed)
hmean_speed_stats

30.0

In [34]:
# hmean dg library
hmean_stats = statistics.harmonic_mean(x)
hmean_stats

2.7613412228796843

## geometric mean

perhitungannya misal ada data 5 x1 dikali x5 dikali akar pangkat 5.

- perusahaan terdiri pd th 2017 
- di th 2017 omsetnya 1000
- di th 2018 naik 30%
- di th 2019 naik 50%
- di th 2020 naik 40%

In [35]:
x = 1000
x*=1.3 #1300
x*=1.5
x*=1.4
x

2730.0

In [36]:
1300 * 1.5

1950.0

In [37]:
(30+50+40)/4 # aritmatic mean

30.0

In [38]:
x = 1000
x*=1.4 
x*=1.4
x*=1.4
x

2743.9999999999995

In [39]:
# geometric mean
gmean = ((30*50*40)**(1/3))
gmean

39.148676411688626

In [40]:
x = 1000
x*=1.3915
x*=1.3915
x*=1.3915
x

2694.322835875

In [41]:
scipy.stats.gmean([30,50,40]) # geometric mean menggunakan library scipy

39.14867641168864

## median

[1,2,4,8,9]

median = 4

n = 5


In [42]:
# ganjil
a = [1,2,4,8,9]
n = len(a)
median = a[2]
median

4

In [43]:
a = [1,2,4,8]
len(a)

4

In [44]:
# genap
a = [1,2,4,8]
n = len(a)
(n+1)/2
median = (2+4)/2
median

3.0

In [154]:
# Menggunakan numpy
x = [8, 1, 2.5, 4, 28]
c = [2,3,4,5]
np.median(c)

3.5

In [155]:
# manual pembuktian
def median_function(x):
    n = len(x)
    if n%2 == 1: #pengecekan apk jml data ganjil atau genap
        median_ = sorted(x)[round(0.5*(n-1))] # ambil median
    else: #genap
        x_ord, index = sorted(x) , round(0.5*n)
        median_ = 0.5 * (x_ord[index-1]+x_ord[index])
    return median_

In [156]:
median_function(x)

4

In [157]:
median_function(c)

3.5

In [158]:
sorted(x)

[1, 2.5, 4, 8, 28]

In [159]:
n = len(x)
round(0.5*(n-1))

2

In [160]:
n

5

# mode/modus

nilai yng paling banyak muncul atau frekuensi pling tinggi

In [140]:
u = [2,3,2,8,12]

mode_ = max((u.count(i),i)for i in set(u))[1]

In [141]:
max([(u.count(i),i)for i in set(u)])[1]

2

In [142]:
[(u.count(i),i)for i in set(u)]

[(1, 8), (2, 2), (1, 3), (1, 12)]

In [143]:
set(u)

{2, 3, 8, 12}

In [144]:
u.count(2)

2

In [145]:
statistics.mode(u)

2

In [146]:
scipy.stats.mode(u)[0][0]

C:\Users\ACER\AppData\Local\Temp\ipykernel_5588\4097402543.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(u)[0][0]


2

In [147]:
mode_lib = scipy.stats.mode(u)

C:\Users\ACER\AppData\Local\Temp\ipykernel_5588\1318742610.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_lib = scipy.stats.mode(u)


In [148]:
u

[2, 3, 2, 8, 12]

In [149]:
u_series = pd.Series(u)
u_series.mode()

0    2
dtype: int64

In [150]:
u_array = np.array(u)
statistics.mode(u_array)

2

In [151]:
v = pd.Series([1,2,3,3,3,np.nan])
v.mode()

0    3.0
dtype: float64

In [152]:
statistics.mode(v)

3.0

In [153]:
h = [1,2,3,3,3,np.nan,np.nan,np.nan,np.nan]
statistics.mode(h)

nan

- series akan mengabaikan nan dan list akan mempertimbangkan nan

# measures of variability

# variance

In [64]:
x

[8, 1, 2.5, 4, 28]

In [65]:
n = len(x)
mean_var = np.mean(x)
var_ = sum((item-mean_var)**2 for item in x ) / (n-1)
var_

123.19999999999999

In [66]:
# menggunakan variance w/ statistic library
var_stat = statistics.variance(x)
var_stat

123.2

In [67]:
var_np = np.var(x,ddof=1)
var_np

123.19999999999999

In [68]:
z = pd.Series(x)
z.var()

123.19999999999999

# standard deviasi

# quiz
- hitung variance
- standart deviasi

In [69]:
x = [1,2,3,6,7,8,30,40,50]

std_dev = statistics.stdev(x)
print("Standar Deviasi dari x adalah:", std_dev)

variance = statistics.variance(x)
print("Variansi dari x adalah:", variance)


Standar Deviasi dari x adalah: 18.58090417606205
Variansi dari x adalah: 345.25000000000006


In [70]:
# secara manual
x = [1,2,3,6,7,8,30,40,50]
n = len(x)
mean = sum(x)/n
var_ = sum((item - mean)**2 for item in x)/(n-1)
Sd_ = var_**(1/2)

print(var_)
print(Sd_)

345.25000000000006
18.58090417606205


In [71]:
var_np

123.19999999999999

In [72]:
stdev = var_np**(1/2)

In [73]:
stdev

11.099549540409285

In [74]:
stdev = np.sqrt(var_np)
stdev

11.099549540409285

In [75]:
x = [8, 1, 2.5, 4, 28]

In [76]:
x

[8, 1, 2.5, 4, 28]

In [77]:
stdev = statistics.stdev(x)
stdev

11.099549540409287

In [78]:
stdev = np.std(x,ddof=1)
stdev

11.099549540409285

# skewness

kita dpt positif skiw atau negatif skiw
- positif di kiri
- negatif kanan

In [79]:
x

[8, 1, 2.5, 4, 28]

In [80]:
n = len(x)

mean = np.mean(x)
stdev = statistics.stdev(x)
skew_ = (sum((item - mean)**3 for item in x))*n /((n-1) * (n-2) *(stdev**3))
skew_

1.947043227390592

In [81]:
scipy.stats.skew(x,bias=False)

1.9470432273905927

In [82]:
z = pd.Series(x)
z.skew()

1.9470432273905924

In [83]:
scipy.stats.skew(x_with_nan)

nan

In [84]:
z_with_nan = pd.Series(x_with_nan)
z_with_nan.skew()

1.9470432273905924

In [85]:
scipy.stats.skew(z_with_nan)

nan

# percentiles

- pembagian data menjadi 100 bagian, misal 1 persentil itu adl satu bagian dr 100 data.
- masing masing bagian data persensinya 1/100
- kuartil angka terbesat di 4

In [86]:
x =[-5,-1.1,0.1,2,8,12.8,21,25.8,41]
np.percentile(x,5) # percentil 5

-3.44

In [87]:
np.percentile(x,0)

-5.0

In [88]:
np.percentile(x,100)

41.0

In [89]:
np.percentile(x,90)

28.840000000000003

In [90]:
statistics.quantiles(x,n=2)

[8.0]

In [91]:
statistics.quantiles(x,n=4)

[-0.5, 8.0, 23.4]

In [92]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

In [93]:
np.quantile(x,0)

-5.0

In [94]:
np.quantile(x,1)

41.0

In [95]:
np.quantile(x,0.01)

-4.688

In [96]:
np.quantile(x,0.5)

8.0

In [97]:
x 

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [98]:
x_with_nan = [-5, -1.1,np.nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]
x_with_nan

[-5, -1.1, nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [99]:
np.quantile(x_with_nan,0)

nan

In [100]:
np.nanquantile(x_with_nan,0.5)

8.0

In [101]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

# ranges

In [102]:
x # range = 41 - (-5) = 46

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [103]:
# np.ptp untuk menghitung range
np.ptp(x)

46.0

In [104]:
np.amax(x) - np.amin(x)

46.0

In [105]:
np.amin(x)

-5.0

In [106]:
np.amax(x)

41.0

# interquartile range (q3-q1) biasanya digunakan u' mendeteksi outlier)

In [107]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [124]:
quartiles = np.quantile(x,[0.25,0.75])
IQR = quartiles[1] - quartiles[0]
IQR

10.0

# SUMMARY OF DESC, STATS

In [165]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [166]:
result = scipy.stats.describe(x,ddof=1,bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [167]:
(result.variance)**(1/2)

15.12454774346805

In [168]:
result.minmax[1]-result.minmax[0]

46.0

In [169]:
result.skewness

0.9249043136685094

In [170]:
z = pd.Series(x)
z

0    -5.0
1    -1.1
2     0.1
3     2.0
4     8.0
5    12.8
6    21.0
7    25.8
8    41.0
dtype: float64

In [171]:
z.describe()

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

# correlation

In [113]:
x = list(range(-10,11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_ar, y_ar = np.array(x),np.array(y)
x_s,y_s = pd.Series(x),pd.Series(y)

In [131]:
len(x)==len(y)

True

# covariance

n = len(x)
mean_x = np.mean(x)
mean(y) = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y) for item in range(n)))/(n-1)
cov_xy

In [176]:
n = len(x)
mean_x = np.mean(x)
mean_y = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y) for item in range(n)))/(n-1)
cov_xy

30.925

In [133]:
cov_matrix = np.cov(x,y)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [116]:
np.var(x,ddof=1)

38.5

In [117]:
np.var(y,ddof=1)

13.914285714285711

In [134]:
cov_xy = cov_matrix[0,1]
cov_xy

19.95

In [135]:
cov_xy = cov_matrix[1,0]
cov_xy

19.95

# correlation coefficient

r = 1 / r = -1 atau mendekati merupakan tanda kedua variabel mengalami multicollinarily

In [136]:
var_x = np.var(x,ddof=1)
var_y = np.var(y,ddof=1)
cov_xy
std_x = var_x**(1/2)
std_y = var_y**(1/2)
r = cov_xy / (std_x*std_y)
r

0.861950005631606

korelasi positif sangat kuat karena mendekati 1

In [138]:
r , p = scipy.stats.pearsonr(x,y)
r

0.8619500056316058

In [137]:
cov_xy

19.95

In [121]:
var_x

38.5

In [139]:
std_x

6.2048368229954285

In [177]:
p

5.122760847201207e-07

In [180]:
xy_corr = scipy.stats.pearsonr(x,y).statistics
xy_corr

ValueError: x and y must have the same length.

In [181]:
corr_matrix = np.corrcoef(x,y)
corr_matrix

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 9 and the array at index 1 has size 21

## pada 2D array

In [183]:
a = np.array([[1,1,1],
             [2,3,1],
             [4,9,2],
             [8,27,4],
             [16,1,1]])

In [184]:
np.mean(a)

5.4

In [185]:
np.median(a)

2.0

In [186]:
np.mean(a,axis=0)

array([6.2, 8.2, 1.8])

In [187]:
np.mean(a,axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [188]:
np.var(a,ddof=1)

53.40000000000001

In [ ]:
np.var(a,ddof=1

In [ ]:
# pada dataframe

In [189]:
row_names = ['first','second','third','fourth','fifth']
col_names=['A','B','C']
df = pd.DataFrame(a,index=row_names,columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [190]:
np.mean(df.A)

6.2

In [192]:
df['A'].mean()

6.2

In [193]:
np.var(df,ddof=1)

A     37.2
B    121.2
C      1.7
dtype: float64

In [194]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [196]:
df.mean(axis=0)

A    6.2
B    8.2
C    1.8
dtype: float64

In [197]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64