In [1]:
c = '34'
c.isnumeric()

True

In [2]:
try:
    int('sd')
except:
    print('bukan integer')

bukan integer


In [2]:
array_1 = [1,2,3,4,5,6,7,8]

In [3]:
array_1[3:]

[4, 5, 6, 7, 8]

## Import numpy

In [6]:
import numpy as np

In [7]:
c = np.array([1,2,3])

In [8]:
c

array([1, 2, 3])

## One dimensional array

In [9]:
c[1]

2

In [10]:
array_1 = np.array([1,2,3,4,5,6,7,8])

In [11]:
array_1[3:]

array([4, 5, 6, 7, 8])

In [12]:
array_1.shape

(8,)

## 2 dimensional array consists of list of lists

In [13]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
array_2 = np.array(list_of_lists)
array_2
print(array_2.shape)

(3, 3)


In [15]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
array_2 = np.array(list_of_lists)
array_2
print(array_2.shape)

(3, 3)


In [14]:
list_of_lists_2 =[[1,2],[3,4],[5,6]]
array_3 = np.array(list_of_lists_2)
print(array_3.shape)
array_3

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
array_2 = np.array(list_of_lists)
array_2
print(array_2.shape)

NameError: name 'np' is not defined

In [4]:
list_of_lists_2 =[[1,2],[3,4],[5,6]]
array_3 = np.array(list_of_lists_2)
print(array_3.shape)
array_3

NameError: name 'np' is not defined

In [9]:
n = int(input("Masukkan tinggi bagian atas dan bawah (bilangan ganjil): "))
if n % 2 == 0:
    n -= 1
for i in range(n//2+1):
    for j in range(i):
        print(" ", end="")
    for k in range(n-2*i):
        print("*", end="")
    print()
for i in range(n//2, 0, -1):
    for j in range(i-1):
        print(" ", end="")
    for k in range(n-2*i+2):
        print("*", end="")
    print()

Masukkan tinggi bagian atas dan bawah (bilangan ganjil):  8


*******
 *****
  ***
   *
  ***
 *****
*******


In [10]:
batas_bawah = int(input('Masukka batas bawah :'))
batas_atas = int(input('Masukka batas atas :'))

for angka in range(batas_bawah, batas_atas + 1):
   if angka > 1:
       for i in range(2, angka):
           if (angka % i) == 0:
               break
       else:
           print(angka)

Masukka batas bawah : 10
Masukka batas atas : 30


11
13
17
19
23
29


## Creating array

In [5]:
# np.zeros
print(np.zeros(8)) #1D
print(np.zeros([3,2])) #2D

NameError: name 'np' is not defined

In [16]:
# np.zeros
print(np.zeros(8)) #1D
print(np.zeros([3,2])) #2D

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
# np.ones
print(np.ones(4))
print(np.ones([4,2]))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# np.empty
np.empty(5)
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# np.arange
print(np.arange(10))
print(np.arange(0,10,2)) #(start,stop,step)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [20]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [21]:
c = np.array([1,2,3,4,3,2,1,5,6,7,8,9])

#append
print(np.append(c,[10,11]))
#delete
print(np.delete(c,2))
#sort
print(np.sort(c))

[ 1  2  3  4  3  2  1  5  6  7  8  9 10 11]
[1 2 4 3 2 1 5 6 7 8 9]
[1 1 2 2 3 3 4 5 6 7 8 9]


In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
c = np.array([1,2,3,4,3,2,1,5,6,7,8,9,10])
d = np.zeros((2,2))
#ndim
print(c.ndim)
print(d.ndim)

#size
print(c.size)
print(d.size)

#reshape
print(c[:-1].reshape(3,4))

1
2
13
4
[[1 2 3 4]
 [3 2 1 5]
 [6 7 8 9]]


In [24]:
array_3 = np.array([[1,2,3,4]])
array_4 = np.array([[5,6,7,8]])
np.vstack([array_3,array_4])
print(np.hstack([array_3,array_4]))

[[1 2 3 4 5 6 7 8]]


In [25]:
array_5 = np.array([1,2,3,4])
array_6 = np.array([5,6,7,8])
np.hstack([array_5,array_6])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
np.append(array_3,[5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
#np.newaxis
array_4 = np.array([4,5,6])
array_4[np.newaxis]
print(array_4[:,np.newaxis].shape)

(3, 1)


In [28]:
#np.expand_dims
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7,axis=1)
array_9 = np.expand_dims(array_7,axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


## Operasi matematika pada array sifatnya broadcast

In [29]:
array_7 = np.array([3,4,5,6,7,8,9])
array_7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [30]:
array_10 = np.array([[1,2,3],[4,5,6]])
array_10-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

## Filtering Array

In [31]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==8])
print(array_7[array_7<=4])

[6 7 8 9]
[8]
[3 4]


In [32]:
array_11 = np.array([[3,5,7],[8,9,10],[-1,-2,-3]])
array_11.shape
print(array_11[array_11>5])

[ 7  8  9 10]


## hstack, vstack, hsplit, vsplit

In [33]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('Stack secara Vertikal')
print(np.vstack([array_14,array_15]))
print('Stack secara Horizontal')
print(np.hstack([array_14,array_15]))

Stack secara Vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [34]:
#hsplit
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [35]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,2))
print('Vertical Split')
print(np.vsplit(array_19,2))

(2, 4)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
Vertical Split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [36]:
#vsplit
array_19 = np.array([[1,2,3,4,5,6],[4,5,6,7,5,6]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,3))
print('Vertical Split')
print(np.vsplit(array_19,3))

(2, 6)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]]), array([[5, 6],
       [5, 6]])]
Vertical Split


ValueError: array split does not result in an equal division

## Operasi Aritmetik antar 2 array

In [37]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [38]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [39]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0))

6
21
[5 7 9]


In [40]:
array_c = np.array([[1,2,3],[4,5,6]])
print(array_c)
print(array_c.sum(axis=0))
print(array_c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [41]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[5 2 3]
 [4 5 6]]
[5 5 6]
[4 2 3]


## Transposing

In [42]:
array_c = np.array([[5,2,3],[4,5,6]])
print(array_c)
print(array_c.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)


In [43]:
print(array_c.T)
print(array_c.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


In [44]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d)
print(array_d.shape)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
(3, 5)


In [45]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d.T)
print(array_d.T.shape)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [46]:
array_random = np.random.random([3,2])*100
print(array_random)

[[67.52037434 50.87491639]
 [82.66675384 28.53355613]
 [35.41587945 92.84836393]]


In [47]:
array_random = np.random.random([3,2,3])*100
print(array_random)
print(array_random.flatten())

[[[49.42527317 20.57879174 36.42249941]
  [10.25361576 62.58337073 94.03371437]]

 [[57.77475668 94.42088588 52.30632946]
  [64.71622945 31.9499515  58.49237233]]

 [[29.56720764 72.00805321 87.34746937]
  [92.22133785 21.0101299  62.86604371]]]
[49.42527317 20.57879174 36.42249941 10.25361576 62.58337073 94.03371437
 57.77475668 94.42088588 52.30632946 64.71622945 31.9499515  58.49237233
 29.56720764 72.00805321 87.34746937 92.22133785 21.0101299  62.86604371]


## Numpy math formulas

In [48]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[ 8.70047557 14.2989315 ]
 [56.08551851 35.57203069]
 [95.54645433 80.22932167]]


290.43273227302745

In [49]:
np.square(9)

81

In [50]:
np.sqrt(9)

3.0

In [51]:
a = np.log(1000000)
print(a)

13.815510557964274


In [52]:
np.exp(a)

999999.9999999995

## Prime number generator based on interval

In [53]:
print('saadfs \n fdf')

saadfs 
 fdf


In [54]:
for i in range(5):
    print(i)

0
1
2
3
4


In [55]:
import numpy as np
a = np.array([3,2,1])

In [56]:
a[0]

3

In [57]:
np.empty((2,2))

array([[0.e+000, 1.e-323],
       [2.e-323, 3.e-323]])

In [58]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [59]:
a = np.array([1,2,3,4])

In [60]:
a

array([1, 2, 3, 4])

In [61]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [62]:
a2.shape

NameError: name 'a2' is not defined

In [63]:
a2.shape

NameError: name 'a2' is not defined

In [64]:
a2

NameError: name 'a2' is not defined

In [65]:
b = np.expand_dims(a,axis=0)

In [66]:
b

array([[1, 2, 3, 4]])

In [68]:
c = np.array([[1,2,3],[3,4,5],[6,7,8]])
c
d = c.copy()

In [69]:
c[c>2]

array([3, 3, 4, 5, 6, 7, 8])

In [70]:
np.vstack([c,d])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
c.sum(axis=1)

array([ 6, 12, 21])

In [73]:
we = c*+2

In [74]:
we

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [12, 14, 16]])

In [75]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
x = c.copy()

In [77]:
y = c+2

In [78]:
np.dot(x,c)

array([[ 25,  31,  37],
       [ 45,  57,  69],
       [ 75,  96, 117]])

In [79]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
np.append(c,[1,2,3,0])

array([1, 2, 3, 3, 4, 5, 6, 7, 8, 1, 2, 3, 0])

In [81]:
q = np.array([1,2,3,0])
np.delete(q,1)

array([1, 3, 0])

In [82]:
np.sort(q)

array([0, 1, 2, 3])

In [83]:
q.sort()

In [84]:
q

array([0, 1, 2, 3])

In [85]:
c.shape

(3, 3)

In [86]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
7%3

1